name: Asity
title: Asity
description: Asity is a lightweight abstraction layer for various web frameworks on the Java Virtual Machine, which is designed to achieve and exploit "Write Once, Run Anywhere" by establishing an ecosystem of universally reusable web fragments that run across different frameworks in the Java ecosystem.
url: http://asity.cettia.io/
author:
  name: Donghwan Kim
  email: flowersinthesand@gmail.com
  twitter: flowersits
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
sass:
    style: compressed
twitter:
  username: flowersits
social:
  links:
    - https://github.com/cettia/asity
    - https://twitter.com/flowersits
    - http://groups.google.com/group/cettia
