name: Asity
description: Asity is a lightweight abstraction layer for I/O frameworks which is designed to build applications that can run on any full-stack framework, any micro framework or any raw server on the JVM.
url: http://asity.cettia.io/
author:
  name: Donghwan Kim
  email: flowersinthesand@gmail.com
relative_permalinks: false
kramdown:
  input: GFM
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
