name: Asity
title: Asity
description: Asity is a lightweight abstraction layer for various web frameworks on the Java Virtual Machine, which is designed to build asynchronous web applications including reusable server-side web components and high-level frameworks on top of HTTP and WebSocket, and run them seamlessly across different full-stack frameworks, micro frameworks and raw servers in the Java ecosystem.
url: http://asity.cettia.io/
author:
  name: Donghwan Kim
  email: flowersinthesand@gmail.com
  twitter: flowersits
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
sass:
    style: compressed
twitter:
  username: cettia_project
social:
  links:
    - https://github.com/cettia/asity
    - https://twitter.com/cettia_project
    - http://groups.google.com/group/cettia
