name: Asity
description: Asity.
url: http://asity.cettia.io/
author:
  name: Donghwan Kim
  email: flowersinthesand@gmail.com
relative_permalinks: false
kramdown:
  input: GFM
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
