name: Asity
title: Asity
description: Asity is a lightweight abstraction layer for various web frameworks on the Java Virtual Machine. It is designed to build asynchronous web applications that can run on any full-stack framework, any micro framework or any raw server on the JVM without any modification whatsoever, and provides HTTP and WebSocket abstractions.
url: http://asity.cettia.io/
author:
  name: Donghwan Kim
  email: flowersinthesand@gmail.com
  twitter: flowersits
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
sass:
    style: compressed
twitter:
  username: cettia_project
social:
  links:
    - https://github.com/cettia/asity
    - https://twitter.com/cettia_project
    - http://groups.google.com/group/cettia
